homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret hass_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  # external files
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend: 

# Tack this on the end to load a frontend file
#!include frontend.yaml

# Enable iOS frontend
ios:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret http_certificate
  ssl_key: !secret http_key
  trusted_networks: !secret trusted_networks
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Use MariaDB Add-on for Database
recorder:
  db_url: !secret mysql_uri

# Enable logging
logger:
  default: warn

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Home Assistant Cloud
cloud:

weblink:
  entities:
    - name: Home Assistant Webpage
      url: https://home-assistant.io/
    - name: Home Assistant Forum
      url: https://community.home-assistant.io/
    - name: Home Assistant Chat
      url: https://discordapp.com/channels/330944238910963714/330944238910963714

################################################################################
# Core Components
################################################################################

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
device_tracker: !include device_tracker.yaml
light: !include lights.yaml
#scene: !include scenes.yaml
#weather: !include weather.yaml

################################################################################
# Inputs
################################################################################
input_datetime:
  bed_time:
    name: Bedtime
    has_date: false
    has_time: true
    initial: 21:00

input_select:
  ian_status_dropdown:
    name: Ian
    options:
      - Home
      - Just Arrived
      - Just Left
      - Work
      - School
      - Away
      - Extended Away
    initial: Home

  aimee_status_dropdown:
    name: Aimee
    options:
      - Home
      - Just Arrived
      - Just Left
      - Work
      - School
      - Away
      - Extended Away
    initial: Home

  richard_status_dropdown:
    name: Richard
    options:
      - Home
      - Just Arrived
      - Just Left
      - Work
      - School
      - Away
      - Extended Away
    initial: Home
################################################################################

#############################
### Additional Components ###
#############################

### MQTT ###
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

# Pushover
notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

# Splunk
splunk:
  host: !secret splunk_host
  token: !secret splunk_token
  port: 8088
  ssl: false
  name: HomeAssistant
  
# IFTTT
ifttt:
  key: !secret ifttt_key
