## General Configuration ##
hass_name: Home Assistant
http_password: password
hass_url: home-assistant.io
hass_port: 8123
latitude: 37.331911
longitude: -122.030249
elevation: 0
timezone: America/Los_Angeles
state_abbreviation: CA

## Core Components ##

## HTTP ##
http_certificate: ssl.crt
http_key: ssl.key
trusted_networks:
  - 127.0.0.1
  - ::1

## Sensors ##
darksky_api_key: apikey

## Media Players ##
plex_username: username
plex_password: password
plex_server: server
plex_token: token
plex_host: plex.example.com
plex_port: 32400
apple_tv_living_room_ip: 127.0.0.1
apple_tv_living_room_login_id: numbers
apple_tv_living_room_credentials: stuff
apple_tv_master_bedroom_ip: 127.0.0.1
apple_tv_master_bedroom_login_id: numbers
apple_tv_master_bedroom_credentials: stuff

## Security System ##
envisalink_ip: 127.0.0.1
envisalink_password: password
envisalink_port: 9999
alarm_code: code

## Notifications ##
pushover_api_key: apikey
pushover_user_key: userkey

## Device Trackers ##
automatic_client_id: clientid
automatic_secret: secret
automatic_username: username
automatic_password: password

## Splunk ##
splunk_host: host
splunk_token: token

## IFTTT ##
ifttt_key: key

## Zoning Details ##

# Home
home_lat: 37.331911
home_long: -122.030249
# Work
ian_work_name: Ian's Workplace
ian_work_lat: 37.331911
ian_work_long: -122.030249
# Gym
gym_lat: 37.331911
gym_long: -122.030249
# Work
richard_work_name: Richard's Workplace
richard_work_lat: 37.331911
richard_work_long: -122.030249
# School
school_name: School
school_lat: 37.331911
school_long: -122.030249
# Work
aimee_work_name: Aimee's Workplace
aimee_work_lat: 37.331911
aimee_work_long: -122.030249
# Aldi
aldi_lat: 37.331911
aldi_long: -122.030249
# Walmart
walmart_lat: 37.331911
walmart_long: -122.030249

# Steam API
steam_api_key: apikey

# Last.fm
lastfm_api_key: apikey
lastfm_shared_secret: sharedsecret

# Ring
ring_username: username
ring_password: password

# Nest
nest_client_id: clientid
nest_client_secret: clientsecret

# Hue
hue_bridge_ip: 127.0.0.1

# Wink
wink_email: email
wink_password: password
wink_client_id: clientid
wink_client_secret: clientsecret

# UniFi
unifi_host: host
unifi_port: 8443
unifi_username: username
unifi_password: password

# Google Cloud Messaging
gcm_api_key: apikey
gcm_sender_id: senderid

# Weather Underground
wunderground_api_key: apikey

# HomeKit Pin
homekit_pin: pin

# MySQL
mysql_uri: mysql://hass:mypassword@localhost/hassdb?charset=utf8

# MQTT
mqtt_username: username
mqtt_password: password

# Yahoo Weather
yweather_woeid: woeid

# Samsung TVs
basement_tv_ip: localhost
living_room_tv_ip: localhost

# Octoprint
octoprint_host: localhost
octoprint_api_key: apikey
octoprint_name: name

# Addon URLs
node-red_url: http://localhost
ide_url: http://localhost
terminal_url: http://localhost
jupyter_url: http://localhost